### ISSUE TITLE
TypeError: Class constructor MediaQuerySplittingPlugin cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Jugibur** [elambro/extract-css-media-queries#2]
Hi, 
I'm trying to include your plugin with Webpack via the postcss.config.js file.
Unfortunately the following error is thrown:
`
ERROR in ./src/scss/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Class constructor MediaQuerySplittingPlugin cannot be invoked without 'new'
    at LazyResult.runOnRoot (we-are-athlon-boilerplate/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (we-are-athlon-boilerplate/node_modules/postcss/lib/lazy-result.js:355:26)
    at LazyResult.async (we-are-athlon-boilerplate/node_modules/postcss/lib/lazy-result.js:205:30)
    at LazyResult.then (we-are-athlon-boilerplate/node_modules/postcss/lib/lazy-result.js:190:17)
    at processResult (we-are-athlon-boilerplate/node_modules/webpack/lib/NormalModule.js:597:19)
    at we-are-athlon-boilerplate/node_modules/webpack/lib/NormalModule.js:691:5
    at we-are-athlon-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at we-are-athlon-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (we-are-athlon-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (we-are-athlon-boilerplate/node_modules/postcss-loader/dist/index.js:103:7)
 @ ./src/js/app.js 1:0-26
`

This is my postcss.config.js:

> module.exports = {
>   plugins: [
>     require('autoprefixer'),
>     require('@elambro/extract-css-media-queries')
>   ],
> };

**Comment by elambro** [comment]
Try this:

```
const ExtractCssMediaQueries = require('@elambro/extract-css-media-queries');
const options = {
  // your breakpoints, filename, etc
}

module.exports = {
    plugins: [
        require('autoprefixer'),
        new ExtractCssMediaQueries(options)
    ],
};
```

**Comment by Jugibur** [comment]
Thanks, the error is now gone but I have a new one :-/
`Loading PostCSS "options" plugin failed: Cannot find module 'options'`

I've tried three Webpack starter kits and build my own with a tutorial – always the same error. Until yet I haven't found an answer with google.

Have **postcss-loader@5.0.0** and **postcss@8.2.4** installed (with Webpack 5)

May I ask what are your environments/settings?

**Comment by elambro** [comment]
@Jugibur It seems you didn't define the `options` object. Can I close this now?

**Comment by Jugibur** [comment]
yes
